### Main test
GET http://localhost:3000

### Get all Products
GET http://localhost:3000/products

### Get prodcut by Id
GET http://localhost:3000/products/4

### Register new user
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "laura_la_guapa@laguapa.com",
  "password": "piter",
  "firstname": "Laura",
  "lastname": "Guasch"
}